# Generated by Django 4.0.1 on 2022-01-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'L'), ('perempuan', 'P')], max_length=9)),
            ],
        ),
    ]
