# Generated by Django 4.0.1 on 2022-01-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
